import 'package:flutter/material.dart';

import 'terminal_title.dart';
import 'text_viewer.dart';

Widget terminalSide(BuildContext context) => SizedBox(
      height: MediaQuery.of(context).size.height,
      child: Column(
        children: [
          terminalTitle(context),
          const Expanded(child: SizedBox()),
          terminalViewer(
            textList: const [
              'Hello',
              '2',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3',
              '3'
            ],
          ),
          const Expanded(child: SizedBox()),
        ],
      ),
    );
