name: Choko
on:
    # Runs on pushes targeting the default branch
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-release:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install yq
              uses: shiipou/setup-yq-action@v2.2.0
            - name: Test yq
              run: yq --version
