name: Choko
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-release:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: (Yet Another) Setup yq
              uses: vegardit/gha-setup-yq@1.0.0
            - name: Show folks how to run YQ
              run: |
                  yq --help
            - name: Show version
              run: |
                  yq -r .version pubspec.yaml

            # Example of Modern way of getting the version
            - name: Get version from pubspec.yaml
              id: vars2
              run: echo "version=$(yq -r .version pubspec.yaml)" >> $GITHUB_OUTPUT

            - name: Use the version
              run: echo "The version is ${{ steps.vars.outputs.version }}"

            # Traditional way of getting the version
            - name: Get version from pubspec.yaml
              id: vars
              run: echo "::set-output name=version::$(yq -r .version pubspec.yaml)"

            - name: Use the version
              run: echo "The version is ${{ steps.vars.outputs.version }}"
