name: Choko
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-release:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: setup-yq4
              uses: infovista-opensource/setup-yq4@v0.9.3
            - name: Show folks how to run YQ
              run: |
                  yq --help
