name: Choko
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-release:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install yq
              uses: chrisdickinson/setup-yq@latest
            - name: Show folks how to run YQ
              run: |
                  yq --help
