name: Choko
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-release:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: (Yet Another) Setup yq
              uses: vegardit/gha-setup-yq@1.0.0
            - name: Show folks how to run YQ
              run: |
                  yq --help
