name: Choko
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-release:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: (Yet Another) Setup yq
              uses: vegardit/gha-setup-yq@1.0.0
            - name: Show folks how to run YQ
              run: |
                  yq --help
            - name: Show version
              run: |
                  yq -r .version pubspec.yaml
            - name: Get version from pubspec.yaml
              run: |
                  echo "VERSION=$(yq -r .version pubspec.yaml)" >> $GITHUB_ENV
            - name: Use the version
              run: |
                  echo "The version is ${{ env.VERSION }}"
