name: Combined Workflow
on:
    # Runs on pushes targeting the default branch
    push:
        branches:
            - release
    workflow_dispatch:

jobs:
    build-and-release:
        runs-on: windows-latest
        steps:
            # Checkout the repository
            - name: Checkout
              uses: actions/checkout@v2

            # Setup Java environment for Android app build
            - name: Setup Java
              uses: actions/setup-java@v1
              with:
                  java-version: "13.x"

            # Setup Flutter environment
            - name: Setup Flutter
              uses: subosito/flutter-action@v1

            # Get Flutter dependencies
            - name: Get Dependencies
              run: flutter pub get

            # Build Windows executable
            - name: Build Windows Executable
              run: flutter build windows

            # Upload generated artifact to release
            - name: Upload Artifact to Release
              uses: actions/upload-artifact@v2
              with:
                  name: release-exe
                  path: build\windows\runner\Release

            - name: Move Release to Root
              run: mv ../build/windows/runner/Release .
            
            - name: Archive Release
              uses: thedoctor0/zip-release@0.7.5
              with:
                filename: 'release.zip'
                path: Release

            # Trigger automatic release
            - name: Trigger Release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: "${{ secrets.RELEASE_TOKEN }}"
                  automatic_release_tag: "latest"
                  prerelease: false
                  title: "Development Build"
                  files: |
                      release.zip
